from __future__ import annotations

GROUP_BOUNDARY_POSITION_OFFSET = 0.5

DUMBBELL_CONNECTOR_LINEWIDTH = 1.5
DUMBBELL_CONNECTOR_ZORDER = 1
DUMBBELL_LEFT_POINT_ZORDER = 2
DUMBBELL_RIGHT_POINT_ZORDER = 3

GROUP_BOUNDARY_LINEWIDTH = 1.0
AXIS_TITLE_FONT_SIZE = 12
AXIS_GRID_LINEWIDTH = 0.8

SUBGROUP_CHART_TITLE_FONT_SIZE = 14
LEVELS_CHART_AXIS_PADDING = 3
GAP_WIDTH_CHART_AXIS_PADDING = 1