from __future__ import annotations

from src.types import AxisSpec

SOURCE_SANS_3_FONT_FAMILY = "Source Sans 3"

SHORT_TERM_COLOR = "#A55A1F"
MEDIUM_TERM_COLOR = "#2F5D7E"
CONNECTOR_COLOR = "#A9B0B5"
GRID_COLOR = "#E6E6E6"
TEXT_COLOR = "#222222"

GROUP_BOUNDARY_POSITION_OFFSET = 0.5

DUMBBELL_CONNECTOR_LINEWIDTH = 1.5
DUMBBELL_CONNECTOR_ZORDER = 1
DUMBBELL_LEFT_POINT_ZORDER = 2
DUMBBELL_RIGHT_POINT_ZORDER = 3

GROUP_BOUNDARY_LINEWIDTH = 1.0
AXIS_TITLE_FONT_SIZE = 12
AXIS_GRID_LINEWIDTH = 0.8

SUBGROUP_CHART_TITLE_FONT_SIZE = 11
SUBGROUP_Y_TICK_FONT_SIZE = 8
GROUP_PAIR_LABEL_X_POSITION = -0.04
GROUP_PAIR_LABEL_LINE_OFFSET = 0.18
LEVELS_CHART_AXIS_PADDING = 3
GAP_WIDTH_CHART_AXIS_PADDING = 1

SUBGROUP_LEVELS_X_AXIS = AxisSpec(55, 95, 10)
SUBGROUP_GAP_WIDTH_X_AXIS = AxisSpec(0, 18, 6)

SUBGROUP_CHANGE_HEATMAP_MIN_ABS_CHANGE = 1.0
